### ISSUE TITLE
REAPER v6系への対応

### ISSUE THREAD

**Issue by cyatarow** [Phroneris/ReaperJPN-Phroneris#6]
REAPER v6系への対応予定はありますか?

**Comment by Phroneris** [comment]
編集作業は `develop` ブランチで行っており、そのコミットログ（作業履歴）はこちらで見られます。
→ https://github.com/Phroneris/ReaperJPN-Phroneris/commits/develop

ご覧の通り、今まさに（"Commits on Jul 27, 2020" から）v6対応を進めています！
正式リリースまでもう少しお待ちください。
